### ISSUE TITLE
N+1問題が出ている

### ISSUE THREAD

**Issue by betachelsea** [fjordllc/fjord-books_app#12]
https://github.com/fjordllc/fjord-books_app/blob/c762120d40719d117535ff4d7a9dde6cbe17f22f/app/controllers/users_controller.rb#L4-L6

view側で `user.avatar` を表示する処理をしているため、ActiveStorageでN+1が発生しているようです。
`.with_attached_avatar` で解決するようですが、プラクティスとして扱うためにちょっと変わったブランチ構成になっている状態なので、PullRequestを投げる前に一旦issueとして報告します。
指摘のあった日報: https://bootcamp.fjord.jp/reports/23268

次の2点を確認できれば進められそうだなと思います。
- そもそも修正する方針でOKでしょうか？
- 修正する場合は、`07-follow_users` ~ `99-completed` の各ブランチに対してPullRequestを出す方針で問題ないでしょうか？

**Comment by JunichiIto** [comment]
@betachelsea 報告ありがとうございます！
あー、たしかに今のコードだとN+1になりますね・・・。
お手本のコードとしてはイマイチなので、PRを出してもらうと助かります！ 🙇 

> そもそも修正する方針でOKでしょうか？
> 修正する場合は、07-follow_users ~ 99-completed の各ブランチに対してPullRequestを出す方針で問題ないでしょうか？

どちらもyesです。

https://fjordbootcamp.esa.io/posts/81 （要ログイン）もあわせて参考にしてみてください〜。

**Comment by betachelsea** [comment]
@JunichiIto 参考esaありがとうございます！週末になりそうですが、PullRequest出してみます 👍  しばらくお待ちください！

**Comment by betachelsea** [comment]
まだ各branchへのmergeが終わっていませんが、 `07-follow_users` への変更は適用されたのでcloseします。
